//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class answer
    {
        public int id { get; set; }
        public int question_id { get; set; }
        public int user_id { get; set; }
        public string body { get; set; }
        public byte[] created_at { get; set; }
    
        public virtual question question { get; set; }
        public virtual user user { get; set; }
    }
}
